//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.Razor.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComponentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComponentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sandbox.Razor.Microsoft.AspNetCore.Razor.Language.ComponentResources", typeof(ComponentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C# attribute that will be applied to the current class..
        /// </summary>
        internal static string AttributeDirective_AttributeToken_Description {
            get {
                return ResourceManager.GetString("AttributeDirective_AttributeToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string AttributeDirective_AttributeToken_Name {
            get {
                return ResourceManager.GetString("AttributeDirective_AttributeToken_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the C# attribute that will be applied to the current class..
        /// </summary>
        internal static string AttributeDirective_Description {
            get {
                return ResourceManager.GetString("AttributeDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds the provided expression to the &apos;{0}&apos; property and a change event delegate to the &apos;{1}&apos; property of the component..
        /// </summary>
        internal static string BindTagHelper_Component_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Component_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the culture to use for conversions..
        /// </summary>
        internal static string BindTagHelper_Element_Culture_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Element_Culture_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds the provided expression to the &apos;{0}&apos; attribute and a change event delegate to the &apos;{1}&apos; attribute..
        /// </summary>
        internal static string BindTagHelper_Element_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Element_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the event handler name to attach for change notifications for the value provided by the &apos;{0}&apos; attribute..
        /// </summary>
        internal static string BindTagHelper_Element_Event_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Element_Event_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a format to convert the value specified by the &apos;{0}&apos; attribute. The format string can currently only be used with expressions of type &lt;code&gt;DateTime&lt;/code&gt;..
        /// </summary>
        internal static string BindTagHelper_Element_Format_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Element_Format_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds the provided expression to an attribute and a change event, based on the naming of the bind attribute. For example: &lt;code&gt;@bind-value=&quot;...&quot;&lt;/code&gt; and &lt;code&gt;@bind-value:event=&quot;onchange&quot;&lt;/code&gt; will assign the current value of the expression to the &apos;value&apos; attribute, and assign a delegate that attempts to set the value to the &apos;onchange&apos; attribute..
        /// </summary>
        internal static string BindTagHelper_Fallback_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Fallback_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the event handler name to attach for change notifications for the value provided by the &apos;{0}&apos; attribute..
        /// </summary>
        internal static string BindTagHelper_Fallback_Event_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Fallback_Event_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a format to convert the value specified by the corresponding bind attribute. For example: &lt;code&gt;@bind-value:format=&quot;...&quot;&lt;/code&gt; will apply a format string to the value specified in &lt;code&gt;@bind-value=&quot;...&quot;&lt;/code&gt;. The format string can currently only be used with expressions of type &lt;code&gt;DateTime&lt;/code&gt;..
        /// </summary>
        internal static string BindTagHelper_Fallback_Format_Documentation {
            get {
                return ResourceManager.GetString("BindTagHelper_Fallback_Format_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the parameter name for the &apos;{0}&apos; child content expression..
        /// </summary>
        internal static string ChildContentParameterName_Documentation {
            get {
                return ResourceManager.GetString("ChildContentParameterName_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the parameter name for all child content expressions..
        /// </summary>
        internal static string ChildContentParameterName_TopLevelDocumentation {
            get {
                return ResourceManager.GetString("ChildContentParameterName_TopLevelDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of the type parameter {0} for the {1} component..
        /// </summary>
        internal static string ComponentTypeParameter_Documentation {
            get {
                return ResourceManager.GetString("ComponentTypeParameter_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the &apos;{0}&apos; attribute to the provided string or delegate value. A delegate value should be of type &apos;{1}&apos;..
        /// </summary>
        internal static string EventHandlerTagHelper_Documentation {
            get {
                return ResourceManager.GetString("EventHandlerTagHelper_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to cancel (if cancelable) the default action that belongs to the &apos;{0}&apos; event..
        /// </summary>
        internal static string EventHandlerTagHelper_PreventDefault_Documentation {
            get {
                return ResourceManager.GetString("EventHandlerTagHelper_PreventDefault_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to prevent further propagation of the &apos;{0}&apos; event in the capturing and bubbling phases..
        /// </summary>
        internal static string EventHandlerTagHelper_StopPropagation_Documentation {
            get {
                return ResourceManager.GetString("EventHandlerTagHelper_StopPropagation_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declares an interface implementation for the current class..
        /// </summary>
        internal static string ImplementsDirective_Description {
            get {
                return ResourceManager.GetString("ImplementsDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interface type implemented by the current class..
        /// </summary>
        internal static string ImplementsDirective_TypeToken_Description {
            get {
                return ResourceManager.GetString("ImplementsDirective_TypeToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeName.
        /// </summary>
        internal static string ImplementsDirective_TypeToken_Name {
            get {
                return ResourceManager.GetString("ImplementsDirective_TypeToken_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensures that the component or element will be preserved across renders if (and only if) the supplied key value matches..
        /// </summary>
        internal static string KeyTagHelper_Documentation {
            get {
                return ResourceManager.GetString("KeyTagHelper_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declares a layout type for the current document..
        /// </summary>
        internal static string LayoutDirective_Description {
            get {
                return ResourceManager.GetString("LayoutDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interface type implemented by the current document..
        /// </summary>
        internal static string LayoutDirective_TypeToken_Description {
            get {
                return ResourceManager.GetString("LayoutDirective_TypeToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeName.
        /// </summary>
        internal static string LayoutDirective_TypeToken_Name {
            get {
                return ResourceManager.GetString("LayoutDirective_TypeToken_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark the page as a routable component..
        /// </summary>
        internal static string PageDirective_Description {
            get {
                return ResourceManager.GetString("PageDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An optional route template for the component..
        /// </summary>
        internal static string PageDirective_RouteToken_Description {
            get {
                return ResourceManager.GetString("PageDirective_RouteToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route template.
        /// </summary>
        internal static string PageDirective_RouteToken_Name {
            get {
                return ResourceManager.GetString("PageDirective_RouteToken_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;@{0}&apos; directive specified in {1} file will not be imported. The directive must appear at the top of each Razor file.
        /// </summary>
        internal static string PageDirectiveCannotBeImported {
            get {
                return ResourceManager.GetString("PageDirectiveCannotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if whitespace should be preserved, otherwise false..
        /// </summary>
        internal static string PreserveWhitespaceDirective_BooleanToken_Description {
            get {
                return ResourceManager.GetString("PreserveWhitespaceDirective_BooleanToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve.
        /// </summary>
        internal static string PreserveWhitespaceDirective_BooleanToken_Name {
            get {
                return ResourceManager.GetString("PreserveWhitespaceDirective_BooleanToken_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether or not whitespace should be preserved exactly. Defaults to false for better performance..
        /// </summary>
        internal static string PreserveWhitespaceDirective_Description {
            get {
                return ResourceManager.GetString("PreserveWhitespaceDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populates the specified field or property with a reference to the element or component..
        /// </summary>
        internal static string RefTagHelper_Documentation {
            get {
                return ResourceManager.GetString("RefTagHelper_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merges a collection of attributes into the current element or component..
        /// </summary>
        internal static string SplatTagHelper_Documentation {
            get {
                return ResourceManager.GetString("SplatTagHelper_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constraints applied to the type parameter..
        /// </summary>
        internal static string TypeParamDirective_Constraint_Description {
            get {
                return ResourceManager.GetString("TypeParamDirective_Constraint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type parameter constraint.
        /// </summary>
        internal static string TypeParamDirective_Constraint_Name {
            get {
                return ResourceManager.GetString("TypeParamDirective_Constraint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declares a generic type parameter for the generated component class..
        /// </summary>
        internal static string TypeParamDirective_Description {
            get {
                return ResourceManager.GetString("TypeParamDirective_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the type parameter..
        /// </summary>
        internal static string TypeParamDirective_Token_Description {
            get {
                return ResourceManager.GetString("TypeParamDirective_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type parameter.
        /// </summary>
        internal static string TypeParamDirective_Token_Name {
            get {
                return ResourceManager.GetString("TypeParamDirective_Token_Name", resourceCulture);
            }
        }
    }
}
